[workspace]
resolver = "3"

package.license = "AGPL-3.0-only"
package.authors = [
  "Keitaroh Kobayashi <keita@kotobamedia.com>"
]
members = [
  "crates/api", "crates/chatter", "crates/cli", "crates/data",
]
